### ISSUE TITLE
Layout does not work on MS Office products

### ISSUE THREAD

**Issue by Morl99** [jonasdiemer/EurKEY-Mac#11]
Hello,

this is more a cry for help than a bug report, but I wasn't sure where to put it. 

Thanks for creating the EurKEY-Mac adaption, it is great. Unfortunately, the MS Office product suite simply ignores the layout, and I have no clue on how to use the layout in powerpoint, word, Outlook, OneNote, ...

I installed the layout in my system settings just fine, and it works within the browser, terminal, IDE, ... But once I open an MS Office product, the input switcher in my status bar jumps back to the default layout that was shipped with my Mac. And if I try to choose EurKEY, I simply can't, clicking it does not make any difference at all.

<img width="279" alt="Screenshot 2022-02-17 at 16 25 47" src="https://user-images.githubusercontent.com/475516/154513706-daab5375-d091-4be4-b545-abb13dc9d813.png">

I would appreciate any pointers, on how to resolve this.

**Comment by jonasdiemer** [comment]
On my Macs, EURKey works also inside the MS Office app. Maybe check your system settings if per-app layout (not exactly sure of the name) is enabled.

**Comment by steffakasid** [comment]
Place the Keyboard file in `/Library/Keyboard Layouts` instead `~/Library/Keyboard Layouts` and restart your Mac. That should solve the issue.

**Comment by Morl99** [comment]
For me, the files were already installed globally, but now, after rebooting the system, it works correctly. 

Thanks for the input.
