### ISSUE TITLE
Producing a dash

### ISSUE THREAD

**Issue by paulkre** [jonasdiemer/EurKEY-Mac#12]
I can't figure out how to type a dash character (`—`) with the EurKEY v1.2 layout. Is this possible?

**Comment by moritzsternemann** [comment]
Yes it's possible! But I struggled to figure out in the beginning as well...

To type the different length dash characters, you have to press `Shift + Option + 7`, then release the keys and press either `1`, `2`, or `3`.

|`-`|`-`||
|`-`|`-`||

**Comment by paulkre** [comment]
Thank you, this worked!
