### ISSUE TITLE
Compatibility for iPadOS 

### ISSUE THREAD

**Issue by PatrickHie** [jonasdiemer/EurKEY-Mac#15]
Is there a way to add EurKEY to iPadOS, currently?

If not is there a way to make EurKEY useable with (software and) hardware keyboards?

All the best
Patrick

**Comment by jonasdiemer** [comment]
This rep is for Mac only. 

For iOS, it should be possible to develop a custom SW keyboard. But it would be a separate project. 

Also, it should be possible to implement EURkey in programmable keyboards (eg via QMK) such as the one from KeyChron, NuType and the likes.
