### ISSUE TITLE
Seems not to work with MacOS Sierra 

### ISSUE THREAD

**Issue by DrTom** [jonasdiemer/EurKEY-Mac#5]
The layout does not appear in the select list in Mac OS Sierra 10.12.2 after proceeding according to the README. Any ideas how to make it work?

**Comment by lbschenkel** [comment]
I have used this layout as my primary layout since the Sierra release. Are you sure that you copied to the file to `~/Library/Keyboard Layouts` and logged out/in again? It should appear in the list and work.

**Comment by DrTom** [comment]
Resolved! Google-Chrome added txt `.txt` extention to the layout which I copied blindly over to `/Libarry/Keyboard Layouts/`.
