### ISSUE TITLE
Not able to get characters like ∑ or ∆ although they are defined in the keylayout file

### ISSUE THREAD

**Issue by danielschlitt** [jonasdiemer/EurKEY-Mac#6]
I don't get how to use keyMap (index 6), which includes some unique characters not found in any other keyMap. For example ∑ or ∆.

I can see those characters within the keyboard overview (see attached image) when I press alt/option + cmd. Problem with cmd key is, that it will execute shortcuts on system level (closing applications and stuff).

Specified modifier keys, somewhere around line 35 of the keylayout file:
`<keyMapSelect mapIndex="6">
<modifier keys="caps? anyOption command"/>
</keyMapSelect>`

![eurkey_v1_1_und_new_issue_ _jonasdiemer_eurkey-mac](https://user-images.githubusercontent.com/2598417/28023088-216f1132-658d-11e7-96c0-8f46e9af93c9.jpg)

**Comment by jonasdiemer** [comment]
Not at my Mac right now, but on Windows you just press AltGr+m, then the
character from the map (e.g. AltGr+m then s for sigma).

2017-07-10 16:38 GMT+02:00 perfectcircle <notifications@github.com>:

**Comment by perfectcircle** [comment]
Most of the characters seen in the above screenshot are accessible with other keystroke combinations/dead key combinations. But my question is: If this set (holding alt/option and command key + any key) was created for Mac, how would you be able to access them as intended.

**Comment by jonasdiemer** [comment]
Hi @danielschlitt!

Is this still actual? Just tried with the latest version, it seems to work for me. I.e. pressing `option+m`, then `shift+s`, I get Σ (an Ω is displayed first, but get's replaced by Σ once `shift+s` is pressed).
